name: Build Scraper EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pyInstaller
        run: pip install pyinstaller

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Set Playwright browsers path and install Chromium
        run: |
          $env:PLAYWRIGHT_BROWSERS_PATH="0"
          playwright install chromium

      - name: Build data_scraper EXE        
        run: |
          $env:DB_SERVER="${{ secrets.DB_SERVER }}"
          $env:DB_DATABASE="${{ secrets.DB_DATABASE }}"
          $env:DB_USERNAME="${{ secrets.DB_USERNAME }}"
          $env:DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          pyinstaller --onefile --hidden-import=pyodbc --collect-data=emoji data_scraper.py
        
      - name: Build link_scraper EXE     
        run: |
          $env:DB_SERVER="${{ secrets.DB_SERVER }}"
          $env:DB_DATABASE="${{ secrets.DB_DATABASE }}"
          $env:DB_USERNAME="${{ secrets.DB_USERNAME }}"
          $env:DB_PASSWORD="${{ secrets.DB_PASSWORD }}"   
          pyinstaller --onefile --hidden-import=pyodbc link_scraper.py

      - name: List files in dist
        run: dir dist

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scrapers
          path: |
            dist/data_scraper.exe
            dist/link_scraper.exe
    
      - name: Release new version
        uses: softprops/action-gh-release@v1
        with:
          name: "Latest Scrapers"
          tag_name: latest
          files: |
            dist/data_scraper.exe
            dist/link_scraper.exe
          draft: false
          prerelease: false